// Copyright (c) 2025, Antoine Duval
// This file is part of a source-visible project.
// See LICENSE for terms. Unauthorized use is prohibited.

//#region Imports

import { Injectable } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

//#endregion

@Injectable({
  providedIn: 'root'
})
export class GlobalService {
  //#region Attributes

  // Express server port, randomly generated by the server when the program is launched.
  public serverPort: number = 0;

  // User's operating system.
  public os?: NodeJS.Platform;

  // User's operating system.
  public devMode: boolean = false;

  // Block the entire interface under a loading display.
  public loading: boolean = false;

  /** URL to access the EBP Discord server. */
  public readonly discordServerURL: string = 'https://discord.gg/tAHAc9q3aX';

  public betaUsers: number[] = [];

  //#endregion

  constructor(private readonly translateService: TranslateService) {}

  //#region Functions

  /** URL to access the EBP website. */
  public get webSiteURL(): string {
    return `https://evabattleplan.com/${this.translateService.currentLang}`;
  }

  public static random(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  //#endregion
}
